# output: modpacks
name: Open Skies

mc_version: "1.12.2"

forge: 2587 # `version`(-recommended /-latest) or branch-name

urls: true
userFiles_include:
 - test
provider_settings:
  curse:
    <<: *curse_settings
    optional: true
    release_types:
      - Release
      - Beta
      - Alpha

  local:
    <<: *local_settings
    folder: local

mods:

  - <<: *curse
    name: MCMultiPart

  - <<: *curse
    name: Botania

  - <<: *curse
    name: Thermal Dynamics

  - <<: *curse
    name: Thermal Expansion

  - <<: *curse
    name: Thermal Cultivation

  - <<: *curse
    name: Extra Utilities

  - <<: *curse
    name: "/dank/null"

  - <<: *curse # it a curse mod
    name: Quark

  - <<: [*curse, *client]
    name: Mouse Tweaks

  - <<: *direct
    url: https://unascribed.com/foamfix/FoamFixUnofficial-1.12.2-0.8.4-Anarchy.jar

  - <<: [*curse, *client]
    name: "AppleSkin"

  - <<: *curse
    name: "Just Enough Items (JEI)"

  - <<: *curse
    name: "Compact Machines"

  - <<: [*curse, *client]
    name: "NoNausea"

  - <<: *curse
    name: OpenComputers

  - <<: *curse
    name: Actually Additions

  - <<: *curse
    name: "Chisel"

  - <<: *curse
    name: "Chisels & Bits"

  - <<: *curse
    name: RFTools

  - <<: *curse
    name: RFTools Dimensions

  - <<: *curse
    name: Immersive Engineering

  - <<: *curse
    name: Immersive Tech

  - <<: *curse
    name: Immersive Petroleum

  - <<: *curse
    name: OpenBlocks

  - <<: *curse
    name: JourneyMap

  - <<: *curse
    name: Waystones

  - <<: *curse
    name: "Embers"

  - <<: *curse
    name: "Astral Sorcery"

  - <<: *curse
    name: "Wizardry Mod"

  - <<: *curse
    name: "Roots"

  - <<: *curse
    name: "MagicBooks2"

  - <<: *curse
    name: NotEnoughIDs

  - <<: *curse
    name: "Just Enough Resources (JER)"

  - <<: *curse
    name: "Tinkers Construct"

  - <<: *curse
    name: "Better Builder's Wands"

  - <<: *direct
    url: https://addons-origin.cursecdn.com/files/2456/43/BiblioCraft%5Bv2.4.3%5D%5BMC1.12.0%5D.jar

  - <<: *curse
    name: "Mouse Tweaks"

  - <<: *curse
    name: Colytra

  - <<: *curse
    name: Refined Storage

  - <<: *curse
    name: Storage Drawers

  - <<: *curse
    name: Integrated Tunnels

  - <<: *curse
    name: Industrial Foregoing

  - <<: *curse
    name: FTB Utilities

  - <<: *curse
    name: Mod Name Tooltip

  - <<: *curse
    name: Tails

  - <<: *direct
    url: https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/128/artifact/build/libs/Charset-0.5.0.128.jar

  - <<: *direct
    url: https://asie.pl/files/mods/Charset/CharsetPatches-0.1.3.jar

  - <<: *direct
    url: https://ci.elytradev.com/job/elytra/job/Thermionics/job/master/40/artifact/build/libs/Thermionics-MC1.12_ver1.1.1.jar

  - <<: *jenkins
    jenkins_url: https://ci.elytradev.com
    job: elytra/Smores/1.12.2
    name: Smores

  - <<: *direct
    url: https://ci.elytradev.com/job/elytra/job/BetterBoilers/job/master/30/artifact/build/libs/BetterBoilers-master-1.1.31.jar

  - <<: *jenkins
    jenkins_url: https://ci.elytradev.com
    job: elytra/ArchitectureCraft/1.12
    name: Architecturecraft

  - <<: *jenkins
    jenkins_url: https://ci.elytradev.com
    job: elytra/ProbeDataProvider/1.12
    name: ProbeDataProvider

  - <<: *jenkins
    jenkins_url: https://ci.elytradev.com
    job: elytra/FruitPhone/1.12
    name: FruitPhone
    depends:
      required:
        - ProbeDataProvider
